# Traveling Salesman Problem (TSP)

### Read in File and Save Weights of all the edges

In [3]:
import glob
import numpy as np

# Get path for all text files in current directory
text_files = glob.glob('*.txt')
print(text_files)

with open(text_files[0], 'r') as f:
    N = f.readline()    # Number of nodes
    print(f'Number of nodes: {N}')
    edges = np.zeros((int(N), int(N)))

    next(f) # Skip the next line
    for line in f:
        n1, n2, d = line.split()
        edges[int(n1)-1, int(n2)-1] = d
        edges[int(n2)-1, int(n1)-1] = d

print(edges)

['1000_euclidianDistance.txt', '1000_randomDistance.txt']
Number of nodes: 1000

[[ 0.   26.98 53.74 ... 26.86 44.96 19.49]
 [26.98  0.   72.27 ... 51.52 64.98 13.02]
 [53.74 72.27  0.   ... 30.73  9.36 59.29]
 ...
 [26.86 51.52 30.73 ...  0.   21.37 40.19]
 [44.96 64.98  9.36 ... 21.37  0.   52.17]
 [19.49 13.02 59.29 ... 40.19 52.17  0.  ]]


In [19]:
from Lin_Kernighan import LKAlgorithm

LK = LKAlgorithm(edges)
tour, dist = LK.optimize()
print(f"Best path has length {dist}")
print(f"Best path is {tour}")

KeyboardInterrupt: 